### ISSUE TITLE
Click to Languages on top left below photograph takes to John's Profile

### ISSUE THREAD

**Issue by drupretys** [MicroHealthLLC/mCMS#235]
![image](https://user-images.githubusercontent.com/33326155/32965129-b1932d1c-cba3-11e7-97a2-c06095c74e76.png)

**Comment by b-solution** [comment]
When the user click 'languages' in breadcrumbs, we should get the page where we can see the languages table. i've added #tabs-model-name to tell the jquery that i want to show me that tabs
we don't have another solution

**Comment by bluenevus** [comment]
@LAlexMHllc  can you show a screenshot sequence to demonstrate how this is supposed to work?

**Comment by LAlexMHllc** [comment]
Nice job on the breadcrumbs solution. Please make the following changes:

1. After user selects a person from SEARCH CLIENT, update the code so that the html address for profile_record does not include the person/id# and the side panel displays Client Profile as active instead of Search Client.
![profile_record](https://user-images.githubusercontent.com/11938477/34052782-d3ac3322-e191-11e7-9922-c03c438ce7a3.jpg)

2. Adjust the display to the top of the screen after address with hash (#). Presently the screen top is inconsistent and the user has to scroll up to the menu tabs.
