### ISSUE TITLE
for the intranet side of the app, can we add the word in bold INTRANET in the middle of the title bar?

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mCMS#263]
![image](https://user-images.githubusercontent.com/3675043/33909257-0c1c5984-df59-11e7-8568-9dc4b350092d.png)

**Comment by LAlexMHllc** [comment]
The logged in user info will need to be removed from that part of the header first.

Example:
Click My Clients menu nav; click My Cases; then click a case title.
Result: Person image/icon will display in the middle of the title bar. 
Note: The rest of user info will display as well, but can't be seen because the text is dark.

![admin_screen_header_bar_user_info](https://user-images.githubusercontent.com/11938477/34117348-6b50cdba-e3e9-11e7-90af-fe69108a489f.jpg)
